// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/identify': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/identify.post').default>>>>
    }
    '/api/collections/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/collections/[id].get').default>>>>
    }
    '/api/collections': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/collections/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/collections/index.post').default>>>>
    }
    '/api/collections/items': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/collections/items.post').default>>>>
    }
    '/api/media': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/media/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/media/index.post').default>>>>
    }
    '/api/push/notify': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/push/notify.post').default>>>>
    }
    '/api/push/subscribe': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/push/subscribe.post').default>>>>
    }
    '/api/quotes': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/quotes/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/quotes/index.post').default>>>>
    }
    '/api/sightings/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sightings/[id].get').default>>>>
    }
    '/api/sightings': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sightings/index.get').default>>>>
    }
    '/api/upload-url': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/upload-url.post').default>>>>
    }
    '/api/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/index.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}